name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Docker tags
      run: docker tag 0e5574283393 vsecoder/vsecoder:$(date +%s)

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vsecoder/vsecoder:$(date +%s)

    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/vsecoder
