name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/vsecoder/vsecoder:$(date +%s)

    - name: Docker push
      run: docker push docker.io/vsecoder/vsecoder:$(date +%s)
